-- Type annotations only; this file is not listed in the TOC and never runs in-game.
-- It exists so the Lua language server can type the `...` vararg every file receives.
-- Every file should start with:
--   ---@type string, BetterGroupLoot
--   local appName, app = ...
-- When a file adds something to `app`, add a matching ---@field here.

---@class BetterGroupLoot
---@field logger BetterGroupLoot.Logger
---@field addon BetterGroupLoot.Addon
---@field dbDefaults BetterGroupLoot.DBDefaults
---@field db BetterGroupLoot.DB
---@field options BetterGroupLoot.Options  # the AceConfig options, in the Settings panel and a standalone window
---@field api BetterGroupLoot.Api  # the client's loot API behind one interface (src/api/)
---@field rolls BetterGroupLoot.Rolls  # the roll frames, their anchor and the preview

-- The AceDB object, with profile/char/global narrowed to the shape of app.dbDefaults.
-- Ace3 API types (AceAddon, AceDBObject-3.0, ...) come from the ketho.wow-api extension.
---@class BetterGroupLoot.DB : AceDBObject-3.0
---@field profile BetterGroupLoot.DB.Profile
---@field char BetterGroupLoot.DB.Char
---@field global BetterGroupLoot.DB.Global
